CREATE TABLE assassin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT(5) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    speed INT(5) NOT NULL,
    strength INT(5) NOT NULL,
    busy BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);